package myhibernatetest;
// Generated 02.03.2015 3:22:42 by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int customerid;
     private String forename;
     private String surname;

    public Customer() {
    }

    public Customer(int customerid, String forename, String surname) {
       this.customerid = customerid;
       this.forename = forename;
       this.surname = surname;
    }
   
    public int getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(int customerid) {
        this.customerid = customerid;
    }
    public String getForename() {
        return this.forename;
    }
    
    public void setForename(String forename) {
        this.forename = forename;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

public String toString(){
    return "id: "+this.getCustomerid()+" name:"+ this.getForename()+ " lastname: "+ this.getSurname();
}


}


